version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/My-Node-JS-Web-Application/web-app
hooks:
  BeforeInstall:
    - location: 
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: 
      timeout: 300
      runas: ubuntu
      script: "cd /home/ubuntu/My-Node-JS-Web-Application/web-app; npm start"
